// Stress at an interior point via the stress Somigliana identity.
//
//   σ_ij(s) = ∫_Γ D*_kij(s, q) t_k(q) dΓ - ∫_Γ S*_kij(s, q) u_k(q) dΓ
//
// Companion to interiorEval.ts (displacement). Same boundary loop and
// quadrature rule — just swaps the kernels.
//
// Singularity warning: D* ~ 1/r and S* ~ 1/r² near the boundary.
// Acceptable only for `p` strictly inside the domain — i.e. for the
// post-process interior nodes generated by the canvas, not for the
// BEM nodes themselves. Callers should guard against the near-boundary
// case (post-process triangulation vertices on Γ).

import { gaussLegendre } from "../numerics/gaussLegendre.js";
import {
  shapeFunctions,
  shapeFunctionDerivatives,
  STANDARD_NODES,
} from "../elements/shapeFunctions.js";
import type { MeshElement } from "../elements/discretise.js";
import type { Vec2 } from "../geometry/types.js";
import {
  effectiveNu,
  shearModulus,
  type MaterialProperties,
} from "./kernels.js";
import {
  kelvinStressKernels,
  type StressTriple,
} from "./stressKernels.js";

const ANCHORS = STANDARD_NODES.continuous;
const INTERIOR_RULE = gaussLegendre(10);

/** Returns σ_ij at `p` from the solved boundary field on `mesh`. */
export function interiorStress(
  p: Vec2,
  mesh: readonly MeshElement[],
  material: MaterialProperties,
): StressTriple {
  const nu = effectiveNu(material);
  const G = shearModulus(material);

  let sxx = 0;
  let syy = 0;
  let sxy = 0;

  for (const el of mesh) {
    const a0 = el.anchors[0];
    const a1 = el.anchors[1];
    const a2 = el.anchors[2];
    const n0 = el.nodes[0];
    const n1 = el.nodes[1];
    const n2 = el.nodes[2];

    for (let q = 0; q < INTERIOR_RULE.nodes.length; q++) {
      const eta = INTERIOR_RULE.nodes[q]!;
      const w = INTERIOR_RULE.weights[q]!;

      const Ng = shapeFunctions(eta, ANCHORS);
      const dNg = shapeFunctionDerivatives(eta, ANCHORS);
      const xField: Vec2 = {
        x: Ng[0] * a0.x + Ng[1] * a1.x + Ng[2] * a2.x,
        y: Ng[0] * a0.y + Ng[1] * a1.y + Ng[2] * a2.y,
      };
      const dxde_x = dNg[0] * a0.x + dNg[1] * a1.x + dNg[2] * a2.x;
      const dxde_y = dNg[0] * a0.y + dNg[1] * a1.y + dNg[2] * a2.y;
      const J = Math.hypot(dxde_x, dxde_y);
      const n: Vec2 =
        J > 0 ? { x: dxde_y / J, y: -dxde_x / J } : { x: 0, y: 0 };

      const Nf = shapeFunctions(eta, el.localNodes);
      const ufx = Nf[0] * n0.ux + Nf[1] * n1.ux + Nf[2] * n2.ux;
      const ufy = Nf[0] * n0.uy + Nf[1] * n1.uy + Nf[2] * n2.uy;
      const tfx = Nf[0] * n0.tx + Nf[1] * n1.tx + Nf[2] * n2.tx;
      const tfy = Nf[0] * n0.ty + Nf[1] * n1.ty + Nf[2] * n2.ty;

      const k = kelvinStressKernels(p, xField, n, G, nu);
      const Jw = J * w;

      sxx += (k.Dx.sxx * tfx + k.Dy.sxx * tfy) * Jw;
      sxx -= (k.Sx.sxx * ufx + k.Sy.sxx * ufy) * Jw;
      syy += (k.Dx.syy * tfx + k.Dy.syy * tfy) * Jw;
      syy -= (k.Sx.syy * ufx + k.Sy.syy * ufy) * Jw;
      sxy += (k.Dx.sxy * tfx + k.Dy.sxy * tfy) * Jw;
      sxy -= (k.Sx.sxy * ufx + k.Sy.sxy * ufy) * Jw;
    }
  }

  return { sxx, syy, sxy };
}
